
ALTER TABLE ROOT.FACTURE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.INTERVENTION ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.TASK ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.C_USER ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.MAIL ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.DEVICE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.SOFTWARE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.SERVICES ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.CLIENT ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ROOT.FILE_PATH ALTER COLUMN ID RESTART WITH 1;