ALTER TABLE ROOT.TASK DROP CONSTRAINT task_workstation_id_fk;
RENAME TABLE ROOT.WORKSTATION TO DEVICE;
RENAME COLUMN ROOT.TASK.ID_WORKSTATION TO ID_DEVICE; 
ALTER TABLE ROOT.TASK ADD CONSTRAINT task_device_id_fk
        FOREIGN KEY (id_device)
        REFERENCES ROOT.DEVICE(id);
ALTER TABLE ROOT.DEVICE DROP CONSTRAINT workstation_client_id_fk;
ALTER TABLE ROOT.DEVICE DROP CONSTRAINT workstation_file_path_id_fk;
ALTER TABLE ROOT.DEVICE ADD CONSTRAINT device_client_id_fk
        FOREIGN KEY (id_client)
        REFERENCES ROOT.CLIENT(id);
ALTER TABLE ROOT.DEVICE ADD CONSTRAINT device_file_path_id_fk
        FOREIGN KEY (id_file_path)
        REFERENCES ROOT.FILE_PATH(id);